config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  #Salesforce Objects
  namespace :salesforce do
    resources :marketing_strategy__cs
    resources :venue__cs
    resources :opportunities
    resources :accounts
    resources :tasks
  end


  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  #Routes for Self Service Pages
  namespace :self_service do
    match '', :action => 'login'
    get 'home'
    get 'solution'
    get 'submit'
    get 'cases'
    get 'view'
    get 'web_to_case'
    get 'iframe'
    get 'public_solutions'
  end
end

app/controllers/marketing_strategy_cs_controller.rb
class MarketingStrategyCsController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :signed_in_user, except: [:new, :create, :edit, :update]
    
    def index
      @marketing_strategys = Marketing_Strategy__c.all()[0..9]
    end

    def show
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
    end

    def new
      @marketing_strategy = Marketing_Strategy__c.new
      @marketing_strategy.Account__c = (params[:AccountId])
    end

    def create
      marketing_strategy__c = Marketing_Strategy__c.new(params[:marketing_strategy__c])
      user = SFDC_Models::User.first
      marketing_strategy__c.OwnerId = user.Id
        if (marketing_strategy__c.save)
          redirect_to( root_path, :notice => "Marketing Strategy was successfully created.")
        end
    end  

    def edit
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
    end

    def update
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
      @marketing_strategy.update_attributes(params[:marketing_strategy__c])
      redirect_to(marketing_strategy__cs_path, :notice => "Marketing Strategy '#{@marketing_strategy.Name}' was successfully updated.")
    end

    def destroy
      marketing_strategy__c = Task.find(params[:Id])
      marketing_strategy__c.delete
      redirect_to(marketing_strategy__cs_path, :notice => "Marketing Strategy '#{marketing_strategy__c.Subject}' was successfully deleted.")
    end

    private

      def signed_in_user
        unless signed_in?
          store_location
          redirect_to signin_path, notice: "Please sign in."
        end
      end
end 

app/controllers/salesforce/accounts_controller.rb
class Salesforce::AccountsController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :signed_in_user

  def new
    @account = Account.new
  end

  def create
    account = Account.new(params[:account])
    #account.IsRecurrence = false
    #account.IsReminderSet = false
    #account.Priority = "Normal"
    user = SFDC_Models::User.first
    account.OwnerId = user.Id
    account.RecordTypeId = "012E0000000Q0WVIA0"
    account.RecordType = "Account"
    if (account.save)
      redirect_to(accounts_path, :notice => 'Account was successfully created.')
    end
  end

  def index
    @accounts = Account.all()[0..4].sort{ |a,b| a.LastModifiedDate <=> b.LastModifiedDate }.reverse
    
    #This is a horrible way to hack the search bar. Looks like it can't issue a blank request, so I have to set the :Name param to something on the initial load. Once it load any other name or id can be entered. This shouldn't be so difficult, I just can't waste the time on it right now. 
    @name_hack = Account.first.Name
    if params[:Name] == nil and params[:Id] == nil
      params[:Name] = @name_hack
      @account = Account.find_by_Name(params[:Name])
    end
    #end hack

    if params[:Name] != nil
      @account = Account.find_by_Name(params[:Name])
    end

    if params[:Id] != nil
      @account = Account.find(params[:Id])
    end

    #@account = Account.find(params[:Id])
    #@account = Account.find_by_Name(params[:Name])
  end

  def show  
    @account = Account.find(params[:id]) 
    @marketing_strategy = Marketing_Strategy__c.find_by_Account__c("#{@account.Id}")
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    @account.update_attributes(params[:account])
    redirect_to(accounts_path, :notice => "Account '#{@account.Name}' was successfully updated.")
  end

  def destroy
    account = Account.find(params[:Id])
    account.delete
    redirect_to(accounts_path, :notice => "Account '#{account.Name}' was successfully deleted.")
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

end 

app/controllers/salesforce/marketing_strategy_cs_controller.rb
class Salesforce::MarketingStrategyCsController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :signed_in_user, except: [:new, :create, :edit, :update]
    
    def index
      @marketing_strategys = Marketing_Strategy__c.all()[0..9]
    end

    def show
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
    end

    def new
      @marketing_strategy = Marketing_Strategy__c.new
      @marketing_strategy.Account__c = (params[:AccountId])
    end

    def create
      marketing_strategy__c = Marketing_Strategy__c.new(params[:marketing_strategy__c])
      user = SFDC_Models::User.first
      marketing_strategy__c.OwnerId = user.Id
        if (marketing_strategy__c.save)
          redirect_to( root_path, :notice => "Marketing Strategy was successfully created.")
        end
    end  

    def edit
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
    end

    def update
      @marketing_strategy = Marketing_Strategy__c.find(params[:id])
      @marketing_strategy.update_attributes(params[:marketing_strategy__c])
      redirect_to(marketing_strategy__cs_path, :notice => "Marketing Strategy '#{@marketing_strategy.Name}' was successfully updated.")
    end

    def destroy
      marketing_strategy__c = Task.find(params[:Id])
      marketing_strategy__c.delete
      redirect_to(marketing_strategy__cs_path, :notice => "Marketing Strategy '#{marketing_strategy__c.Subject}' was successfully deleted.")
    end

    private

      def signed_in_user
        unless signed_in?
          store_location
          redirect_to signin_path, notice: "Please sign in."
        end
      end
end 

app/controllers/salesforce/opportunities_controller.rb
class Salesforce::OpportunitiesController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :signed_in_user

  def new
      @opportunity = Opportunity.new
      @opportunity.AccountId = (params[:AccountId])
  end

  def create
    opportunity = Opportunity.new(params[:opportunity])
    #opportunity.IsRecurrence = false
    #opportunity.IsReminderSet = false
    #opportunity.Priority = "Normal"
    user = SFDC_Models::User.first
    opportunity.OwnerId = user.Id
    #opportunity.StageName = "Prospecting"
    opportunity.IsPrivate = false
    opportunity.CloseDate = Time.now + 30
    # opportunity.RecordTypeId = "012E0000000Q0WVIA0"
    if (opportunity.save)
      redirect_to(opportunities_path, :notice => 'Opportunity was successfully created.')
    end
  end 

  def index
    @opportunities = Opportunity.all
    opportunity = Opportunity.find(params[:id])
    @opportunity_owner = SFDC_Models::User.find_by_id("#{opportunity.OwnerId}")
  end

  def show  
    @opportunity = Opportunity.find(params[:id]) 
  end

  def edit
    @opportunity = Opportunity.find(params[:id])
  end

  def update
    @opportunity = Opportunity.find(params[:id])
    @opportunity.update_attributes(params[:opportunity])
    redirect_to(opportunities_path, :notice => "Opportunity '#{@opportunity.Name}' was successfully updated.")
  end

  def destroy
    opportunity = Opportunity.find(params[:Id])
    opportunity.delete
    redirect_to(opportunities_path, :notice => "Opportunity '#{opportunity.Name}' was successfully deleted.")
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

end 

app/controllers/salesforce/tasks_controller.rb
class Salesforce::TasksController < ApplicationController
  include Databasedotcom::Rails::Controller

  def new
    @task = Task.new
  end

  def create
    task = Task.new(params[:task])
    task.IsRecurrence = false
    task.IsReminderSet = false
    task.Priority = "Normal"
    user = SFDC_Models::User.first
    task.OwnerId = user.Id
    if (task.save)
      redirect_to(tasks_path, :notice => 'Task was successfully created.')
    end
  end

  def index
    @tasks = Task.all 
  end

  def show  
    @task = Task.find(params[:id]) 
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    redirect_to(tasks_path, :notice => "Task '#{@task.Subject}' was successfully updated.")
  end

  def destroy
    task = Task.find(params[:Id])
    task.delete
    redirect_to(tasks_path, :notice => "Task '#{task.Subject}' was successfully deleted.")
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

end 

app/views/salesforce/marketing_strategy_cs/edit.html.erb
<h1>Editing Marketing Strategy:</h1>
<h2><%= @marketing_strategy.Name %></h2>
<h2>For Account: <%= Account.find("#{@marketing_strategy.Account__c}").Name %> </h2>

<%= form_for @marketing_strategy do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name %>
    </div>
    <div class="field">
        <%= f.label :What_benefits_can_your_venue_provide_to__c %><br />
        <%= f.text_field :What_benefits_can_your_venue_provide_to__c %>
    </div>
    <div class="field">
        <%= f.label :How_is_your_company_currently_perceived__c %><br />
        <%= f.text_field :How_is_your_company_currently_perceived__c %>
    </div>
    <div class="field">
        <%= f.label :What_are_your_key_brand_attributes__c %><br />
        <%= f.text_field :What_are_your_key_brand_attributes__c %>
    </div>
    <div class="field">
        <%= f.label :Do_you_want_to_incorporate_these_key_bra__c %><br />
        <%= f.text_field :Do_you_want_to_incorporate_these_key_bra__c %>
    </div>
    <div class="field">
        <%= f.label :What_s_the_primary_message_you_want_to_d__c %><br />
        <%= f.text_field :What_s_the_primary_message_you_want_to_d__c %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Show', @marketing_strategy %> |
<%= link_to 'Back', marketing_strategy__cs_path %> |
<%= link_to 'Delete', @marketing_strategy, :confirm => 'Are you sure?', :method => :delete %>

app/views/salesforce/marketing_strategy_cs/index.html.erb
<% if flash[:notice] %>
  <% flash[:notice] %><br/><br/>
<% end %>

<h1>Marketing Strategies</h1>

<%= link_to 'New', new_marketing_strategy__c_path(@marketing_strategy) %> |
<%= link_to 'Back', marketing_strategy__cs_path %> 	
<br/>
<br/>

<table class="table">
<tr>
	<th>ID</th>
	<th>Name</th>
	<th>Owner</th>
	<th>Created Date</th>
	<th>Last Modified</th>
</tr>

<% @marketing_strategys.each do |marketing_strategy| %>
<tr>
	<td><%= link_to "#{marketing_strategy.Id}", marketing_strategy %></td>
	<td><%= "#{marketing_strategy.Name}" %></td>
	<td><%# SFDC_Models::User.find_by_id("#{marketing_strategy.OwnerId}").Name %></td>
	<td><%= "#{marketing_strategy.CreatedDate}" %></td>
	<td><%= "#{marketing_strategy.LastModifiedDate}" %></td>
</tr>
<% end %>
</table>
</ul>

app/views/salesforce/marketing_strategy_cs/new.html.erb
<h1>Create Marketing Strategy Record</h1>
<h2>For Account <%= Account.find("#{@marketing_strategy.Account__c}").Name %> </h2>

<%= form_for @marketing_strategy do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name %>
    </div>
    <div class="field">
        <%= f.label :Account__c %><br />
        <%= f.text_field :Account__c %>
    </div>
    <div class="field">
        <%= f.label :What_benefits_can_your_venue_provide_to__c %><br />
        <%= f.text_field :What_benefits_can_your_venue_provide_to__c %>
    </div>
    <div class="field">
        <%= f.label :How_is_your_company_currently_perceived__c %><br />
        <%= f.text_field :How_is_your_company_currently_perceived__c %>
    </div>
    <div class="field">
        <%= f.label :What_are_your_key_brand_attributes__c %><br />
        <%= f.text_field :What_are_your_key_brand_attributes__c %>
    </div>
    <div class="field">
        <%= f.label :Do_you_want_to_incorporate_these_key_bra__c %><br />
        <%= f.text_field :Do_you_want_to_incorporate_these_key_bra__c %>
    </div>
    <div class="field">
        <%= f.label :What_s_the_primary_message_you_want_to_d__c %><br />
        <%= f.text_field :What_s_the_primary_message_you_want_to_d__c %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', marketing_strategy__cs_path %>

app/views/salesforce/marketing_strategy_cs/show.html.erb
<h1>Marketing Strategy:<h1/>
<h2><%= @marketing_strategy.Name %></h2>
<h2>For Account: <%= Account.find("#{@marketing_strategy.Account__c}").Name %> </h2>

<%= link_to 'Edit', edit_marketing_strategy__c_path %> |
<%= link_to 'Back', marketing_strategy__cs_path %>
<br/>
<br/>

<table class="table">
<tr>
	<th>Attribute</th>
	<th>Value</th>
</tr>
<% @marketing_strategy.attributes.each do |a| %>
<tr>
    <td><%= a[0] %>:</td><td><%= a[1] %></td>
</tr>
<% end %>
</table>